### PR TITLE
Bug fix lost annotations on setitem call

### PR DESCRIPTION
**Pull request by adrianlut**
Hello,

because this is my first time creating a pull request and because I am (seemingly) the first person contributing outside the team, I want to shortly introduce myself. I am a computer science student from the University of Rostock and I am currently working on my master's thesis about measuring and analyzing the changes made in data preparation pipelines. I implemented some prototype inspections and checks with the help of mlinspect and found some bugs in the process. Now I want to contribute the fixes.

**Bug description**

If an inspection makes annotations while analyzing a PROJECTION_MODIFY operation caused by a call to `DataFrame.__setitem__()` (or `MlinspectDataFrame`), these annotations are not saved inside the DataFrame. Instead, the DataFrame still containes the annotations from before the operation.

**Fix description**

As you can see in the diff, the fix is quite simple. The result of execute_inspection_visits_unary_operator is now returned by `after_call_used_setkey` and the overridden `__setitem__` method of the `MlinspectDataFrame` updates the annotations from the result.

**Alternative fix**

It is probably also possible to change the annotations of the DataFrame in place instead of copying the annotations from the copy of the DataFrame that `create_wrapper_with_annotations` creates. But that would probably require multiple changes in other places and could have unforeseen consequences in other methods.

### CODE REVIEW

**Comment by stefan-grafberger** [comment]
Hi @adrianlut,

Thanks a lot for your PRs! I'm really happy about mlinspect getting its first external contributions. I'll have a look at the PRs next week.

I would also be very interested in hearing more about what you're using mlinspect for if you're willing to share anything about that at some point.

**Comment by stefan-grafberger** [comment]
Hi @adrianlut,

The change looks great to me, but it would be good also to have a test to verify this and prevent the same bug from occurring again in the future. Would you be willing to add such a test? 

I think the easiest way to add such a test would be to use a simple code snippet string and run mlinspect on it with a simple or mocked test inspection. A test where we call mlinspect on a short code string can be found [here](https://github.com/stefan-grafberger/mlinspect/blob/65d5659868cd5377b346ac37afbcabcb56307fb0/test/instrumentation/test_pipeline_executor.py#L76).

Also, the Travis CI stopped working due to me running out of freely available Travis credits, so I migrated the CI to GitHub Actions earlier today. Would it be possible to merge the latest changes on the `master` branch into your branches or rebase onto the newest master version? Then the CI should automatically run the tests and the linter for the PRs, I think.

**Comment by adrianlut** [comment]
Hallo @stefan-grafberger,

Thank you for the feedback. I already though about adding tests, but I think it will take some time for me to write tests for my three PRs, because I am currently finishing my thesis and have to concentrate on that. I will have a look into it when I have the free time.

I merged the master into all pull request branches.

**Comment by stefan-grafberger** [comment]
Hallo @adrianlut,

Sure, your thesis comes first! In any case, thanks for your contribution :-)

**Comment by stefan-grafberger** [comment]
I just saw that you used the `demo` branch as a base and as a PR target; it would be better to use `master` instead. Sorry about the confusion; we, too, will have to merge the latest changes (or parts of them) we made on `demo` back to `master` once we finished our preparations for our upcoming SIGMOD demo.

**Comment by stefan-grafberger** [comment]
Hi @adrianlut,

Maybe you saw it already; there was a larger rework of mlinspect to support control flow. As a result, your PRs would also need to be updated. Are you still interested in working on this? If you don't have enough time to work on this, I can also finish the PRs :-)  

I think, with the new changes, we might no longer this PR. The annotation order PR should still be applicable without significant changes; only some tests need to be updated. The missing column names topic is a little bit larger. The addition for `pandas.Series` in your PR would still be applicable, though. 

For transformers like the `OneHotEncoder`, that can consume `pandas.DataFrame`s with multiple columns and output a single `numpy.ndarray`, we need to pass the NumPy arrays to the inspections in a way, so they know which parts of the array correspond to which logical columns. 

There are some performance considerations when splitting the NumPy arrays into multiple columns from an inspection perspective (we either need to extend the schema information or add some logic to the `InspectionInputRow` classes and use functions that return partial NumPy views of the original array). The second solution is likely preferable, but we would need to measure its performance overhead.

**Comment by adrianlut** [comment]
Hello @stefan-grafberger,

I will now have a look into it because I have the spare time. The rework really is extensive.

I also think that the annotation order PR is still relevant and easy to port to the new master version. I think I will start with it.

Regarding to the column names I noticed that adding the correct names, especially for the concatenations, caused a number of issues with inspections that depend on the `"array"` names and the correct number of column names. However I still think it would be useful to have the correct names for all inspections.

**Comment by stefan-grafberger** [comment]
That's awesome! Let me know if you have any questions while you work on this.

Yeah, having the correct column names is definitely useful. There are rare cases where it's almost impossible to do this tracking properly through different transformers, e.g., in this example:

```python
from sklearn.feature_selection import  VarianceThreshold
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

X = pd.DataFrame.from_dict({
    'A': [0.87, -1.34,  0.31,  1.92],
    'B': [-1.34, -0.48, -2.55, 0.65],
    'C': [-1.34, -0.48, -2.55, 0.65],
    'D': [0, 0, 0, 0],
})
f_select = VarianceThreshold(threshold=(.8 * (1 - .8)))
standard_scaler = StandardScaler()
pipeline = Pipeline([("f_select", f_select), ("scaler", standard_scaler)])
X = ColumnTransformer([
    ("obscure_example", pipeline, ['B', 'C', 'D'])]

).fit_transform(X)
print(X)
```
If we have feature selection transformers or ones for dimensionality reduction, then it becomes very difficult to track the column names. So I don't think we can always guarantee to provide the correct column names through different transformers. However, we should definitely try to do this tracking on a best-effort basis. 

For transformers like the OneHot Encoder, it's possible to track which values get transformed to which one-hot vector, see, e.g., [this part from before the rework](https://github.com/stefan-grafberger/mlinspect/blob/da6760b1ee54ca0d83675b5763e5860959c8e83b/mlinspect/backends/_sklearn_backend_transformer_wrapper.py#L109). But there might be transformers or other operations where we lose this column-level tracking, e.g., if we want to support `apply`/`map` operations using user-defined functions. If the user-defined function returns a numpy array, then we need some fallback like the current `array`.

**Comment by stefan-grafberger** [comment]
You might also have noticed that the DAG changed slightly as part of the rework. That was in order to deal with issues like the one in this obscure example. Previously, we duplicated transformer nodes that are part of a `ColumnTransformer` so that there's a version of each transformer for each column it transforms. But in code like in the feature selection example above, the DAG then might change depending on the data flowing through it, which we would like to avoid.

**Pull request closed without merging**
